#!/bin/sh
#
# @name Mini Quadrotor SITL FlightGear (DJI Mini 4 Pro sized)
#
# @type Quadrotor X
#
# @maintainer PX4 Development Team
#
# FlightGear-specific airframe mapping matching PX4_SIM_MODEL=flightgear_miniquad
#

. ${R}etc/init.d/rc.mc_defaults

param set-default CA_AIRFRAME 0

param set-default CA_ROTOR_COUNT 4

# Mini quadrotor frame with ~122.5mm arm length (245mm wheelbase / 2)
# X configuration
param set-default CA_ROTOR0_PX 0.0865
param set-default CA_ROTOR0_PY 0.0865
param set-default CA_ROTOR0_KM 0.05

param set-default CA_ROTOR1_PX -0.0865
param set-default CA_ROTOR1_PY -0.0865
param set-default CA_ROTOR1_KM 0.05

param set-default CA_ROTOR2_PX 0.0865
param set-default CA_ROTOR2_PY -0.0865
param set-default CA_ROTOR2_KM -0.05

param set-default CA_ROTOR3_PX -0.0865
param set-default CA_ROTOR3_PY 0.0865
param set-default CA_ROTOR3_KM -0.05

param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_FUNC2 102
param set-default PWM_MAIN_FUNC3 103
param set-default PWM_MAIN_FUNC4 104
